buildpacks = [
  { id = "io.test.java",       uri = "buildpacks/io.test.java/latest" },
  { id = "org.cloudfoundry.buildsystem", uri = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.2.15.tgz" },
  { id = "org.cloudfoundry.openjdk",     uri = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.2.14.tgz" },
  { id = "org.cloudfoundry.springboot",     uri = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.2.13.tgz" },
  { id = "org.cloudfoundry.jvmapplication",     uri = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.1.12.tgz" },
]

[[order]]
group = [
### Order is strictly enforced
  { id = "org.cloudfoundry.openjdk" },
  { id = "org.cloudfoundry.buildsystem",               optional = true },

### Order determines precedence
  { id = "org.cloudfoundry.jvmapplication" },
  { id = "org.cloudfoundry.springboot",                optional = true },
  { id = "io.test.java" },

]

[lifecycle]
version = "0.7.2"

[stack]
id          = "org.cloudfoundry.stacks.cflinuxfs3"
build-image = "cloudfoundry/build:full-cnb"
run-image   = "cloudfoundry/run:full-cnb"
